### ISSUE TITLE
Change `datatx.PullTransfer` to `datatx.CreateTransfer`

### ISSUE THREAD

**Issue by redblom** [cs3org/cs3apis#189]
By design a transfer tool is used for the data transfers. Depending on the tool or configuration transfers can be executed using different methods (streaming, third-party copy push/pull). Currently in our cs3 reference implementation reva we use rclone which supports both streaming and third-party push transfer (https://github.com/cs3org/reva/pull/3491) and we can configure this.

I propose to change `PullTransfer` method from the `datatx` module to `CreateTransfer`.

**Comment by glpatcern** [comment]
Fully agree. If you create the PR here and in Reva, we can review and merge them at the same time to not break compatibility as a method rename is a breaking change.

**Comment by redblom** [comment]
Do you want me to push an updated `proto.lock` file also? I noticed it's lagging behind.

**Comment by glpatcern** [comment]
> Do you want me to push an updated `proto.lock` file also? I noticed it's lagging behind.

Why not, thanks.
