### ISSUE TITLE
Redirection status code

### ISSUE THREAD

**Issue by labkode** [cs3org/cs3apis#27]
To perform redirections on operations we need a redirection status code.

To know where to redirect we need a storage resource reference AND a protocol type.

A storage reference can point to other storage providers inside the CS3 cloud and we can connect to them using the CS3APIs but the reference can point to an OCM share or to a remote storage like a FTP server, therefore we need a protocol type so the client know how to fetch the information from the referenced resource, in case of OCM, webdav.

**Comment by labkode** [comment]
@diocas let me know if I missed something

**Comment by diocas** [comment]
Should we have another ticket for a protocol resolution?

**Comment by labkode** [comment]
For redirection we can base the work on:
https://golang.org/pkg/net/url/#URL

```
 A URL represents a parsed URL (technically, a URI reference).

The general form represented is:

[scheme:][//[userinfo@]host][/]path[?query][#fragment]

URLs that do not start with a slash after the scheme are interpreted as:

scheme:opaque[?query][#fragment]

```


Using URI references we can register `cs3` as scheme handler for storage resource types and `dav` for webdav, plus having the freedom to extend
