### ISSUE TITLE
UserId

### ISSUE THREAD

**Issue by moscicki** [cs3org/cs3apis#4]
Consider if a UserId (identified of a user in the system) should not have a message on its own (instead of just string).

This is to foresee an external scope (as done for ResourceId breaking it into opaque id and storage id).

**Comment by labkode** [comment]
@moscicki I will even require that this is the case for the identity of the user.
Doing that we address two issues:
1) federated setups like Sciebo or Surfsara can have different user management services depending on the institution of the users.
2) OCM shares

Something on the lines ...

```
message UserId {
  string user_provider_id = 1;
  string opaque_id = 2;
}
```
