### ISSUE TITLE
storage: extended attributes / properties

### ISSUE THREAD

**Issue by butonic** [cs3org/cs3apis#5]
Currently, there is no support for additional file / folder metadata like extended attributes. Webdav has properties, which I would like to map onto extended attributes. The cs3 apis should allow doing that.

**Comment by moscicki** [comment]
This is still in the making but we are working on it here: https://github.com/cernbox/cs3apis/blob/review/cs3/storageprovider/v0alpha/resources.proto

**Comment by butonic** [comment]
can we use it for favorites? properties are tied to resources. favorites are depending on the user.

**Comment by butonic** [comment]
it could be a folder of references

**Comment by butonic** [comment]
oc uses webdav properties for favorites, however they do not map wall to arbitrary metadata because favorite flags as well as tags are user individual. I will raise tagging (including favorites) as a separate issue, because, AFAICT it makes more sense to implement them in a dedicated service.

**Comment by butonic** [comment]
fixed with https://github.com/cs3org/cs3apis/pull/31
- allows setting arbitrary metadata
- also introduces CanonicalMetadata https://github.com/cs3org/cs3apis/pull/31#issuecomment-530260184
